useDotenv: true
service: Notes

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: ${env:IAM_ROLE}
  environment:
    USERS_TABLE: notes-accounts
    NOTES_TABLE: notes-notes
    JWT_SECRET_ID: notes-api/${sls:stage}/JWT_SECRET
    JWT_EXPIRES_IN: 1h

functions:
  whoami:
    handler: functions/whoami.handler
    events:
      - httpApi:
          path: /api/whoami
          method: GET

  signup:
    handler: functions/signup.handler
    events:
      - httpApi:
          path: /api/user/signup
          method: POST

  login:
    handler: functions/login.handler
    events:
      - httpApi:
          path: /api/user/login
          method: POST

  getNotes:
    handler: notes/getNote.handler
    events:
      - httpApi:
          path: /api/notes
          method: GET

  createNote:
    handler: notes/createNote.handler
    events:
      - httpApi:
          path: /api/notes
          method: POST

  updateNote:
    handler: notes/updateNote.handler
    events:
      - httpApi:
          path: /api/notes
          method: PUT

  deleteNote:
    handler: notes/deleteNote.handler
    events:
      - httpApi:
          path: /api/notes
          method: DELETE

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-accounts
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-notes
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
